version: "3.8"
services:
  user-service:
    build:
      context: ./userService
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- 
      npx sequelize-cli db:create && 
      npx sequelize-cli db:migrate && 
      npx sequelize-cli db:seed:all && 
      npm start"

  product-service:
    build:
      context: ./productService
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - rabbitmq
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- 
      npx sequelize-cli db:create && 
      npx sequelize-cli db:migrate && 
      npx sequelize-cli db:seed:all && 
      npm start"

  order-service:
    build:
      context: ./orderService
    container_name: order-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- 
           ./wait-for-it.sh rabbitmq:5672 -- 
           npx sequelize-cli db:create && 
           npx sequelize-cli db:migrate && 
           npx sequelize-cli db:seed:all && 
           npm start"

  invoice-service:
    build:
      context: ./invoiceService
    container_name: invoice-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - rabbitmq
    command: >
      sh -c "./wait-for-it.sh mysql:3306 -- 
           ./wait-for-it.sh rabbitmq:5672 -- 
           npx sequelize-cli db:create && 
           npx sequelize-cli db:migrate && 
           npx sequelize-cli db:seed:all && 
           npm start"

  notification-service:
    build:
      context: ./notificationService
    container_name: notification-service
    ports:
      - "8084:8084"
   

  mq-consumer:
    build:
      context: ./mqConsumer
    container_name: mq-consumer
    depends_on:
      - rabbitmq
    command: sh -c "./wait-for-it.sh rabbitmq:5672 -- npm start"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ordermanagementsystem_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  rabbitmq_data: